spring:
  datasource:
    password: postgre
    url: jdbc:postgresql://localhost/olxadvertise
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true